ALTER TABLE als_tiers ADD COLUMN price_micros INTEGER NOT NULL DEFAULT 0;
ALTER TABLE als_tiers ADD COLUMN value_type TEXT NOT NULL DEFAULT '';
ALTER TABLE als_tiers ADD COLUMN value_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE als_tiers ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE als_tiers ADD COLUMN features_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE als_tiers ADD COLUMN is_enabled INTEGER NOT NULL DEFAULT 1;
