ALTER TABLE als_tiers ADD COLUMN price_micros BIGINT NOT NULL DEFAULT 0;
ALTER TABLE als_tiers ADD COLUMN value_type TEXT NOT NULL DEFAULT '';
ALTER TABLE als_tiers ADD COLUMN value_amount BIGINT NOT NULL DEFAULT 0;
ALTER TABLE als_tiers ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE als_tiers ADD COLUMN features_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE als_tiers ADD COLUMN is_enabled BOOLEAN NOT NULL DEFAULT TRUE;
