// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login with email and password and receive session token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/public/articles": {
            "get": {
                "description": "List all published articles for public website.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "List published articles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.publicArticleListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/public/articles/{slug}": {
            "get": {
                "description": "Get one published article by slug.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Get published article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Article slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.publicArticleDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/public/estimate": {
            "post": {
                "description": "Estimate total default price for a tier based on active unit prices.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Estimate tier price",
                "parameters": [
                    {
                        "description": "Estimate payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.publicEstimateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.publicEstimateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/public/tiers": {
            "get": {
                "description": "List all public subscription tiers and included default service items.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "List public tiers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.listPublicTiersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpapi.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "httpapi.listPublicTiersResponse": {
            "type": "object",
            "properties": {
                "tiers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.publicTierResponse"
                    }
                }
            }
        },
        "httpapi.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "httpapi.loginResponse": {
            "type": "object",
            "properties": {
                "session_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/httpapi.loginUserResponse"
                }
            }
        },
        "httpapi.loginUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "httpapi.publicArticleDTO": {
            "type": "object",
            "properties": {
                "author_avatar_url": {
                    "type": "string"
                },
                "author_name": {
                    "type": "string"
                },
                "cover_image_url": {
                    "type": "string"
                },
                "excerpt": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "read_time": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "httpapi.publicArticleDetailDTO": {
            "type": "object",
            "properties": {
                "author_avatar_url": {
                    "type": "string"
                },
                "author_name": {
                    "type": "string"
                },
                "cover_image_url": {
                    "type": "string"
                },
                "excerpt": {
                    "type": "string"
                },
                "mdx_body": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "read_time": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "httpapi.publicArticleDetailResponse": {
            "type": "object",
            "properties": {
                "article": {
                    "$ref": "#/definitions/httpapi.publicArticleDetailDTO"
                }
            }
        },
        "httpapi.publicArticleListResponse": {
            "type": "object",
            "properties": {
                "articles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.publicArticleDTO"
                    }
                }
            }
        },
        "httpapi.publicEstimateItemResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "included_units": {
                    "type": "integer"
                },
                "line_total_micros": {
                    "type": "integer"
                },
                "missing_price": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price_per_unit_micros": {
                    "type": "integer"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "httpapi.publicEstimateRequest": {
            "type": "object",
            "properties": {
                "tier_code": {
                    "type": "string"
                }
            }
        },
        "httpapi.publicEstimateResponse": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.publicEstimateItemResponse"
                    }
                },
                "tier_code": {
                    "type": "string"
                },
                "tier_name": {
                    "type": "string"
                },
                "total_price_micros": {
                    "type": "integer"
                }
            }
        },
        "httpapi.publicTierItemResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "included_units": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "httpapi.publicTierResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "default_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.publicTierItemResponse"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "httpapi.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AI API Portal Backend API",
	Description:      "API documentation for AI API Portal backend service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
